path:
  train_path: ../data/train.csv
  test_path: ../data/dev.csv
  predict_path: ../data/test.csv
  save_path: save_models/

data:
  shuffle: True
  train_ratio: 0.8
  swap: True

model:
  model_name: kykim/funnel-kor-base

train:
  max_epoch: 35
  batch_size: 64
  learning_rate: 0.00002137
  loss: mse
  use_frozen: False
  
utils:
  seed: 42
  monitor: val_pearson
  patience: 100
  top_k: 1

k_fold:
  use_k_fold: False
  num_folds: 3
  num_split: 5
  
wandb:
  project: nlp-08-level1-sts